name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm i
          else
            npm i
          fi

      - name: Lint
        run: npm run lint || echo "Lint warnings only"

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm test -- --ci
